translate 340-349 to Japansese
mohikanz/1on1-questions pull request #24
Opened 2020-02-21 11:51 UTC by shimokei53

resolve #7

2020-02-21 15:06 UTC, gimKondo requested changes
いくつか、私なりの提案をしてみましたので、確認お願いします。
とはいえ、間違ってるとか、日本語としてあまりに不自然な場合以外は、翻訳者の意向を優先したいと思いますので、参考程度に！

2020-02-21 15:06 UTC, gimKondo commented on questions.json
> +        "ja_JP": "日々の仕事で、私との関わりは何パーセントでしょうか？もっと増やしたい/減らしたいですか？"
> 私との関わりは何パーセントでしょうか？
「私が関わっている割合はどのくらいでしょうか？」くらいの方が自然な気がします。
ただ、明確に何パーセントって聞かれた方が、質問としては面白いかもしれませんね。
そういう意図があるなら、この訳もありだと思います！

2020-02-21 15:06 UTC, gimKondo commented on questions.json
> +        "ja_JP": "私がもっと良くできるはずだったことは何ですか？私がもっと助けられたかもしれないが、しなかった状況は何ですか？"
> 私がもっと助けられたかもしれないが、しなかった状況は何ですか？
訳としてはいいと思います。
ちょっと直訳とはズレますが、「私がもっと助けになれたのはどんな場面でしょうか？」とすると日本語としては自然かなと思いますが、どうでしょう？

2020-02-21 15:06 UTC, gimKondo commented on questions.json
> +        "ja_JP": "あなたが私に最も必要としていることは何ですか？"
「私を最も必要とするのはどんなことですか？」とかどうでしょう？

2020-02-21 15:47 UTC, shimokei53 commented on questions.json
> +        "ja_JP": "日々の仕事で、私との関わりは何パーセントでしょうか？もっと増やしたい/減らしたいですか？"
ありがとうございます！
まさにそのような意図があって、数値で答えてもらったほうが面白そうかなと思い `何パーセントか` という質問にしてみました。

ただ確かに日本語としての不自然さを感じていたので、 `私が関わっている割合は何パーセントくらいでしょうか？` という訳にしようかと思っています。
多少の重複表現にはなるかもしれませんが、いかがでしょうか？

2020-02-21 15:51 UTC, shimokei53 commented on questions.json
> +        "ja_JP": "私がもっと良くできるはずだったことは何ですか？私がもっと助けられたかもしれないが、しなかった状況は何ですか？"
ありがとうございます！実際に翻訳をやってみて、なかなか自然な日本語表現が難しいと感じたところでした…💦 

`私がもっと助けになれたのはどんな場面でしょうか？` 
こちらの質問の方が自然ですし、もともとの文意がより伝わりやすいと感じました。修正します！ありがとうございます！

2020-02-21 15:53 UTC, shimokei53 commented on questions.json
> +        "ja_JP": "あなたが私に最も必要としていることは何ですか？"
完全にそちらの方が自然で良いですね…！修正します！ありがとうございます！！

2020-02-21 16:03 UTC, shimokei53 commented
チェックありがとうございます！🙏🙏🙏
うまく意訳できなかったり、日本語表現にかなり迷ったところでしたので、ご提案頂けて大変勉強になりました！！！😆

それぞれ修正しましたので、改めてご確認いただければと思います🙇 宜しくお願いいたします！

2020-02-22 12:57 UTC, gimKondo commented on questions.json
> +        "ja_JP": "日々の仕事で、私との関わりは何パーセントでしょうか？もっと増やしたい/減らしたいですか？"
なるほど、いいと思います！。
日本語としての自然さも考慮して、 `私が関わっているのは何パーセントくらいでしょうか？` とかどうでしょう？

2020-02-22 13:02 UTC, gimKondo approved these changes
1件、感想程度のコメント入れましたが、ご自身で良いと思われればこれで良いと思います。
マージしちゃってください。
![LGTM](https://lgtmoon.herokuapp.com/images/75596)

2020-02-22 13:02 UTC, shimokei53 commented on questions.json
> +        "ja_JP": "日々の仕事で、私との関わりは何パーセントでしょうか？もっと増やしたい/減らしたいですか？"
そちらに修正します！ありがとうございますー！

2020-02-22 13:04 UTC, shimokei53 commented
レビューありがとうございます！入れ違いになりましたが、直しちゃいました！🙏
conflictを修正したらマージします！！

2020-02-22 13:13 UTC, merged