fix: translation
mohikanz/1on1-questions pull request #41
Opened 2020-03-31 12:15 UTC by shun-fix9

fix: translation

2020-03-31 12:23 UTC, shun-fix9 commented
直訳だと `being taken away from that task` => その仕事から連れ去られたこと

そのままでもいいかなと思いました

2020-03-31 17:24 UTC, gimKondo requested changes

2020-03-31 17:24 UTC, gimKondo commented on questions.json
> +        "ja_JP": "もしこの打ち合わせがなかったら何していましたか？ その仕事から連れ去られてここにいることについてどう感じていますか？"
確かに、ちょっと踏み込んだ意訳気味ではありますね。
ただ、直訳の「連れ去る」だとちょっと詩的過ぎる感もあります。
こんな訳ならどうでしょう？

```suggestion
        "ja_JP": "もしこの打ち合わせがなかったら何していましたか？ そのタスクから引き離されたことについてどう感じていますか？"
```

2020-04-01 15:09 UTC, gimKondo approved these changes
この意訳は分かりやすいし、原文の意味も汲み取れてるのでいいですね。
LGTM 👍

2020-04-01 15:09 UTC, merged