fix: word choice
mohikanz/1on1-questions pull request #42
Opened 2020-03-31 12:27 UTC by shun-fix9

fix: word choice

2020-03-31 12:29 UTC, shun-fix9 commented
「見てみたい変化」だと、受動的すぎる気がしました

2020-03-31 17:13 UTC, gimKondo requested changes

2020-03-31 17:13 UTC, gimKondo commented on questions.json
> +        "ja_JP": "チームのことで何か変えたいことはありますか？　それは何故ですか？"
確かに、少し不自然な感じはしますね。
「変えたい」まですると、ちょっと原文のニュアンスが変わってしまう気がするので、こんなのはどうでしょう？

```suggestion
        "ja_JP": "チームのことで何か変わってほしいことはありますか？　それは何故ですか？"
```

2020-04-01 15:08 UTC, gimKondo approved these changes

2020-04-01 15:08 UTC, merged